const actionTypes = Object.freeze({

    // -------------------------- USER ACTION ----------------------------------
    GET_ALL_CODE: 'GET_ALL_CODE',
    GET_ALL_USER_START: 'GET_ALL_USER_START',
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    // GET_SIZE_USERS_START: 'GET_SIZE_USERS',
    CHANGE_STATUS_ACCOUNT_USER: 'CHANGE_STATUS_ACCOUNT_USER',
    ADMIN_LOGIN: 'ADMIN_LOGIN',
    ADMIN_LOGOUT: 'ADMIN_LOGOUT',

    // -------------------------- CATEGORY ACTION ----------------------------------
    GET_ALL_CATEGORY_START: 'GET_ALL_CATEGORY_START',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_HOME_PAGE_START: 'GET_ALL_CATEGORY_HOME_PAGE_START',
    GET_ALL_CATEGORY_HOME_PAGE_SUCCESS: 'GET_ALL_CATEGORY_HOME_PAGE_SUCCESS',
    GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',

    // -------------------------- PRODUCT ACTION ----------------------------------
    GET_ALL_PRODUCT_START: 'GET_ALL_PRODUCT_START',
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    GET_PRODUCT_START: 'GET_PRODUCT_START',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',

    // -------------------------- BLOG ACTION ----------------------------------
    GET_ALL_BLOG_START: 'GET_ALL_BLOG_START',
    GET_ALL_BLOG_SUCCESS: 'GET_ALL_BLOG_SUCCESS',
    GET_BLOG_START: 'GET_BLOG_START',
    GET_BLOG_SUCCESS: 'GET_BLOG_SUCCESS',

    // -------------------------- CART ACTION ----------------------------------
    ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
    UPDATE_QUANTITY_PRODUCT: 'UPDATE_QUANTITY_PRODUCT',
    DELETE_PRODUCT_IN_CART: 'DELETE_PRODUCT_IN_CART',
    DELETE_ALL_PRODUCT_IN_CART: 'DELETE_ALL_PRODUCT_IN_CART',

    // -------------------------- CLIENT ACTION ----------------------------------
    CLIENT_LOGIN: 'CLIENT_LOGIN',
    CLIENT_LOGOUT: 'CLIENT_LOGOUT',
    CLIENT_ORDER_START: 'CLIENT_ORDER_START',
    CLIENT_ORDER_SUCCESS: 'CLIENT_ORDER_SUCCESS',
    CLIENT_ORDER_FAIL: 'CLIENT_ORDER_FAIL',
    GET_ALL_ORDER_BY_USER_ID_START: 'GET_ALL_ORDER_BY_USER_ID_START',
    GET_ALL_ORDER_BY_USER_ID_SUCCESS: 'GET_ALL_ORDER_BY_USER_ID_SUCCESS',

    // -------------------------- ORDER ACTION ----------------------------------
    GET_ALL_ORDER_START: 'GET_ALL_ORDER_START',
    GET_ALL_ORDER_SUCCESS: 'GET_ALL_ORDER_SUCCESS',
})

export default actionTypes